before_script:
  - composer self-update
  - if [ "$(phpenv version-name)" -lt "7" ];
    then pecl install -f inotify-0.1.6; else
    pecl install inotify;
    fi
  - composer install --prefer-dist --no-interaction
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
language: php
matrix: 
  allow_failures: 
  - php: hhvm
addons:
  code_climate:
      repo_token: 9c2e16e1a85bcb2f836d6fa76d8e6b676d905d881862e0545f8977b78efbd034